// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenRPReloaded.Contexts;

#nullable disable

namespace OpenRPReloaded.Migrations
{
    [DbContext(typeof(OpenRPContext))]
    partial class OpenRPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("OpenRPReloaded.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Banned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OpenRPReloaded.Models.Character", b =>
                {
                    b.Property<Guid>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenderIdentity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pronouns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Respect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SexualOrientation")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterID");

                    b.HasIndex("AccountID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("OpenRPReloaded.Models.Character", b =>
                {
                    b.HasOne("OpenRPReloaded.Models.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRPReloaded.Models.Account", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
